name: eisi-website
region: tor
static_sites:
- build_command: npx react-scripts build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: brankoEISI/eisi-website
  name: eisi-website
  output_dir: build
  catchall_document: index.html
  routes:
  - path: /
